### ISSUE TITLE
Distribution on Stitcher

### ISSUE THREAD

**Issue by amsross** [csbookclub/csbookclub.com#18]
Stitcher, while a great podcast consumption platform otherwise, doesn't allow users to add podcasts for their own consumption. Instead they require that the podcast owner submit the podcast to their service.

Any chance of adding CS Book Club to their service?

http://www.stitcher.com/content-faq

> How do I get my show on Stitcher?
> 
> Stitcher is programmed using RSS feeds. You provide us the link to your RSS feed; we load it into the system, program it and process it on an ongoing basis for fast and seamless play over mobile and in-car networks.
> 
> It’s easy! Visit our [sign up form](http://www.stitcher.com/content-providers.php) to submit your show.

**Comment by justincampbell** [comment]
Submitted, thanks!
